resources:
  repositories:
    - repository: 'AlmTemplates'
      type: git
      name: ALM/devops_pipelines
      ref: develop

trigger:
- master

stages:
  - stage: Build
    jobs:
      - job:
        variables:
          buildConfiguration: 'Release'
        pool:
          name: Default
          steps:
          - template: 'templates/.netcore-build.yml@AlmTemplates'
            parameters:
              AppName: 'David dotnet core Test'
              Portfolio: 'ESM'
              # DotNetVersion: '3.x'
              BuildConfiguration: debug
              #DownloadSecureFile: 'false'
              #RunArtifactoryUpload: 'true'
              #Projects: '**/*.sln'
              #TestPath: "**/*Tests/*.csproj"
              RunTests: true
              ZipAfterPublish: false
              SonarScan: true